version: '3.9'

services:
  rate-limiter:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: rate-limiter
    restart: on-failure
    ports:
      - ${RATE_LIMITER_PORT:-8080}:8080
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}